name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout blog builder
        uses: actions/checkout@v3
        with:
          repository: subnader/blog-builder
          ref: v1.1.12
          token: ${{ secrets.GH_PAT }}
          path: ./.github/actions/blog-builder
      
      - name: Deploy
        uses: ./.github/actions/blog-builder
        with:
          branch: blog 
